services:
# use in case of local testing
#  db:
#    container_name: postgres
#    image: postgres:16
#    restart: always
#    shm_size: 128mb
#    expose:
#      - "5432"
#    environment:
#      POSTGRES_PASSWORD: root

  latex-to-pdf:
    container_name: backend
    image: laxman6811/latex-to-pdf:latest
#    links:
#      - db
    build: .
#    depends_on:
#      - db
    env_file:
      - .env.dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app

# TODO: research on ports left
#  rabbitmq:
#    image: rabbitmq:4-management
#    ports:
#      - protocol: tcp
#        target: 15672
#      - protocol: tcp
#        target: 5672